# Generated by Django 5.2.7 on 2025-11-23 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('multiplo', 'Múltiple')], default='multiplo', max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion_detallada', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido/imagenes/')),
                ('video', models.FileField(blank=True, help_text='Formatos: MP4, WebM', null=True, upload_to='contenido/videos/')),
                ('audio', models.FileField(blank=True, help_text='Formatos: MP3, WAV', null=True, upload_to='contenido/audios/')),
                ('archivo_descarga', models.FileField(blank=True, help_text='PDF, documento, etc.', null=True, upload_to='contenido/archivos/')),
                ('datos_historicos', models.TextField(blank=True, help_text='Información histórica/educativa')),
                ('datos_cientificos', models.TextField(blank=True, help_text='Datos científicos o técnicos')),
                ('curiosidades', models.TextField(blank=True, help_text='Curiosidades o anécdotas')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido QR',
                'verbose_name_plural': 'Contenidos QR',
            },
        ),
        migrations.CreateModel(
            name='MuseoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Museo', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('imagen_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Museo',
                'verbose_name_plural': 'Configuración del Museo',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('numero_secuencial', models.IntegerField(help_text='Número de orden en la búsqueda del tesoro')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('url', models.URLField(editable=False, max_length=500, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['numero_secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=5)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moderado', models.BooleanField(default=False, help_text='Aprobado por administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_museo', to=settings.AUTH_USER_MODEL)),
                ('contenido_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='qrmuseum.contenidoqr')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='qrmuseum.qrcode'),
        ),
        migrations.CreateModel(
            name='UsuarioMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo_juego', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('puntos', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('total_qrs_escaneados', models.IntegerField(default=0)),
                ('total_comentarios', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_museo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Museo',
                'verbose_name_plural': 'Usuarios Museo',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(auto_now=True)),
                ('tiempo_permanencia', models.IntegerField(default=0, help_text='Tiempo en segundos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_qr', to=settings.AUTH_USER_MODEL)),
                ('qr_visitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='qrmuseum.qrcode')),
            ],
            options={
                'verbose_name': 'Progreso Usuario',
                'verbose_name_plural': 'Progresos Usuarios',
                'ordering': ['-fecha_visita'],
                'unique_together': {('usuario', 'qr_visitado')},
            },
        ),
    ]
