# Generated by Django 5.2.7 on 2025-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmuseum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museoconfig',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la página', null=True, upload_to='backgrounds/'),
        ),
    ]
