# Generated by Django 5.2.7 on 2025-11-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmuseum', '0002_museoconfig_imagen_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_archivo',
            field=models.BooleanField(default=True, help_text='Mostrar archivo descargable'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_audio',
            field=models.BooleanField(default=True, help_text='Mostrar audio en el contenido'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_cientifico',
            field=models.BooleanField(default=True, help_text='Mostrar información científica'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_curiosidades',
            field=models.BooleanField(default=True, help_text='Mostrar curiosidades'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_historico',
            field=models.BooleanField(default=True, help_text='Mostrar información histórica'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_imagen',
            field=models.BooleanField(default=True, help_text='Mostrar imagen en el contenido'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='mostrar_video',
            field=models.BooleanField(default=True, help_text='Mostrar video en el contenido'),
        ),
        migrations.AddField(
            model_name='contenidoqr',
            name='video_url_externa',
            field=models.URLField(blank=True, help_text='URL de video externo (YouTube, Google Drive, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='contenidoqr',
            name='audio',
            field=models.FileField(blank=True, help_text='Formatos: MP3, WAV, MP4', null=True, upload_to='contenido/audios/'),
        ),
    ]
