# Generated by Django 5.2.7 on 2025-12-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmuseum', '0003_contenidoqr_mostrar_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresousuario',
            name='tiempo_permanencia',
        ),
    ]
